---

- name: Configuring PostgreSQL 1/2
  ansible.builtin.lineinfile:
    path: "{{ rhel_psql_conf_path }}"
    regexp: "(#|^)listen_addresses"
    line: "listen_addresses = '*'"
    owner: postgres
    group: postgres

- name: Configuring PostgreSQL 2/2
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ rhel_psql_hba_conf_path }}"
    owner: postgres
    group: postgres
  notify: restart postgres
