---

- name: Configuring PostgreSQL 1/3
  ansible.builtin.lineinfile:
    path: "{{ debian_psql_conf_path }}"
    regexp: "(#|^)listen_addresses"
    line: "listen_addresses = '*'"
    owner: postgres
    group: postgres

- name: Configuring PostgreSQL 2/3
  ansible.builtin.lineinfile:
    path: "{{ debian_psql_conf_path }}"
    regexp: "(#|^)port"
    line: "port = {{psql_port}}"
    owner: postgres
    group: postgres

- name: Configuring PostgreSQL 3/3
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ debian_psql_hba_conf_path }}"
    owner: postgres
    group: postgres
