---

- name: Installing PostgreSQL
  yum:
    name: postgresql-server
    state: present

- name: Checking if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "{{ rhel_psql_conf_path }}"
  register: pg_initialized

- name: Initializing PostgreSQL DB
  ansible.builtin.command: postgresql-setup --initdb
  when: not pg_initialized.stat.exists
  changed_when: true
