---

- import_tasks: install_Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: config_Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: install_RHEL.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: config_RHEL.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: create_user.yml
