---

- name: Installing firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure firewalld is disabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: false
  when: ansible_os_family == 'RedHat'

- name: Configuring firewalld (1/2)
  ansible.posix.firewalld:
    port: "{{ ssh_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == 'RedHat'

- name: Configuring firewalld (2/2)
  ansible.posix.firewalld:
    port: "{{ psql_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == 'RedHat'

- name: Ensure firewalld is enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  when: ansible_os_family == 'RedHat'
