---

- import_playbook: playbooks/calculate_load.yml
- import_playbook: playbooks/select_target_host.yml

- name: Install and Configure PostgreSQL and Firewall
  hosts: target_host
  roles:
    - postgres
    - firewall