---

- import_playbook: playbooks/calculate_load.yml
- import_playbook: playbooks/select_target_host.yml

- name: Install and Configure PostgreSQL and Firewall
  hosts: target_host
  roles:
    - postgres
    - firewall
  tasks:
    - name: Testing PostgreSQL
      community.postgresql.postgresql_query:
        login_db: "{{ test_db_name }}"
        login_user: "{{ db_user }}"
        query: SELECT 1;
